name: hyper_effects
description: Create beautiful effects and animations with just a few lines of code.

version: 0.4.0

homepage: https://hyperdesigned.dev/
repository: https://github.com/hyper-designed/hyper_effects
issue_tracker: https://github.com/hyper-designed/hyper_effects/issues

screenshots:
  - description: Hyper Effects by hyperdesigned.dev
    path: screenshots/logo.png

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ">=1.11.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  material_ui: ^1.0.0
  flutter_lints: ^6.0.0

flutter:

topics:
  - animation
  - effects
  - transitions
  - scroll-effects
